export   const defaultPadSettings = [
  {id: '1', color: 'yellow', sample: './audio/Samples/Scratch1.wav'},
  {id: '2', color: 'red', sample: './audio/Samples/Horn1.mp3'},
  {id: '3', color: 'purple', sample: './audio/Samples/SynthShot1.wav'},
  {id: '4', color: 'yellow', sample: './audio/Samples/CongaFinger.wav'},
  {id: '5', color: 'purple', sample: './audio/Samples/BassShot3.wav'},
  {id: '6', color: 'purple', sample: './audio/Samples/BassShot2.wav'},
  {id: '7', color: 'green', sample: './audio/Samples/Clap1.wav'},
  {id: '8', color: 'blue', sample: './audio/Samples/Brass1.wav'},
  {id: '9', color: 'blue', sample: './audio/Samples/Brass2.wav'},
  {id: '10', color: 'green', sample: './audio/Samples/Kick1.wav'},
  {id: '11', color: 'green', sample: './audio/Samples/Snare1.wav'},
  {id: '12', color: 'orange', sample: './audio/Samples/Vocal1.wav'},
]

export   const allSamples = [
  {id: '1', name: 'BackSpin 1', path: './audio/Samples/Backspin1.wav'},
  {id: '2', name: 'BackLoop 1', path: './audio/Samples/BassLoop1.wav'},
  {id: '3', name: 'BackLoop 2', path: './audio/Samples/BassLoop2.wav'},
  {id: '4', name: 'Bass Shot 1', path: './audio/Samples/BassShot1.wav'},
  {id: '5', name: 'Bass Shot 2', path: './audio/Samples/BassShot2.wav'},
  {id: '6', name: 'Bass Shot 3', path: './audio/Samples/BassShot3.wav'},
  {id: '7', name: 'Bell 1', path: './audio/Samples/Bell1.wav'},
  {id: '8', name: 'Bongo 1', path: './audio/Samples/Bongo1.wav'},
  {id: '9', name: 'Bongo 2', path: './audio/Samples/Bongo2.wav'},
  {id: '10', name: 'Brass 1', path: './audio/Samples/Brass1.wav'},
  {id: '11', name: 'Brass 2', path: './audio/Samples/Brass2.wav'},
  {id: '12', name: 'Clap 1', path: './audio/Samples/Clap1.wav'},
  {id: '13', name: 'Clap 2', path: './audio/Samples/Clap2.wav'},
  {id: '14', name: 'Clap 3', path: './audio/Samples/Clap3.wav'},
  {id: '15', name: 'Conga Finger', path: './audio/Samples/CongaFinger.wav'},
  {id: '16', name: 'Crash 1', path: './audio/Samples/Crash1.wav'},
  {id: '17', name: 'Glitch 1', path: './audio/Samples/Glitch1.wav'},
  {id: '18', name: 'Glitch 2', path: './audio/Samples/Glitch2.wav'},
  {id: '19', name: 'HiHat 1', path: './audio/Samples/Hihat1.wav'},
  {id: '20', name: 'HiHat 2', path: './audio/Samples/Hihat2.wav'},
  {id: '21', name: 'Horn 1', path: './audio/Samples/Horn1.wav'},
  {id: '22', name: 'Kick 1', path: './audio/Samples/Kick1.wav'},
  {id: '23', name: 'Kick 2', path: './audio/Samples/Kick2.wav'},
  {id: '24', name: 'Kick 3', path: './audio/Samples/Kick3.wav'},
  {id: '25', name: 'Scratch 1', path: './audio/Samples/Scratch1.wav'},
  {id: '26', name: 'Snare 1', path: './audio/Samples/Snare1.wav'},
  {id: '27', name: 'Snare 2', path: './audio/Samples/Snare2.wav'},
  {id: '28', name: 'SynthShot 1', path: './audio/Samples/SynthShot1.wav'},
  {id: '29', name: 'SynthShot 2', path: './audio/Samples/SynthShot2.wav'},
  {id: '30', name: 'Vocal 1', path: './audio/Samples/Vocal1.wav'},
  {id: '31', name: 'Vocal 2', path: './audio/Samples/Vocal2.wav'},
  {id: '32', name: 'Wobble 1', path: './audio/Samples/Wooble1.wav'},
]
